# ─── Fail2Ban: Nginx HTTP Auth filter ────────────────────────────────────────
# File: /etc/fail2ban/filter.d/nginx-http-auth.conf

[Definition]
failregex = ^ \[error\] \d+#\d+: \*\d+ user "\S+":? (password mismatch|was not found in ".*"), client: <HOST>, .*$
            ^ \[error\] \d+#\d+: \*\d+ no user/password was provided for basic authentication, client: <HOST>, .*$
ignoreregex =
