import { ProductFormData, UploadedFile } from "@/types/product";

const initialFormData: ProductFormData = {
  productName: "",
  chemicalName: "",
  description: "",
  tradeName: "",
  chemicalFamily: "",
  polymerType: "",
  industry: [],
  grade: [],
  manufacturingMethod: "",
  physicalForm: "",
  countryOfOrigin: "",
  color: "",
  productImages: [] as UploadedFile[],

  density: "",
  mfi: null,
  tensileStrength: null,
  elongationAtBreak: null,
  shoreHardness: null,
  waterAbsorption: null,
  safety_data_sheet: {},
  technical_data_sheet: {},
  certificate_of_analysis: {},
  minimum_order_quantity: null,
  stock: null,
  uom: "",
  price: null,
  priceTerms: "fixed",
  incoterms: [],
  leadTime: "",
  paymentTerms: "",
  packagingType: [],
  packagingWeight: "",
  storageConditions: "",
  shelfLife: "",
  recyclable: false,
  bioDegradable: false,
  fdaApproved: false,
  medicalGrade: false,
  createdBy: "",
  product_family: [],
};
